language: ruby
script: 'bundle exec rspec spec'
rvm:
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - 2.0.0
matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.ruby-1.8.7
    - rvm: ree
      gemfile: gemfiles/Gemfile.ree
